### ISSUE TITLE
Sample App Rewrite Help

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#655]
**AppIntro Version**: Upcoming

**Issue details / Repro steps / Use case background**: Can I use android architecture components in building the sample App? ( Viewmodel, livedata etc?). I am asking because then it might be a little bit intimidating for new developers checking the code, but AAC really help a lot, so I think we should use it, as the developers anyway go to the readme. So, tell me What do I do.

**Comment by cortinico** [comment]
> I am asking because then it might be a little bit intimidating for new developers checking the code, but AAC really help a lot, so I think we should use it, as the developers anyway go to the readme. So, tell me What do I do.

So generally I think we should keep the Sample App as simple as possible.
I don't really see much value in having AAC in the example app (but please let me know if you have some examples uses case that would make the app benefit of that).

Generally speaking, the app should be used as a starting point where developers can copy-n-paste from. If we add AAC, I'm afraid developers will just assume they need to have AAC in order to use AppIntro.

Moreover AAC are generally useful when working with medium/complex architecture. In our case I don't really mind if we have duplicated code. I would actually call it a plus as developers won't need to checkout the full codebase to understand the sample app.
