### ISSUE TITLE
Customization of done button background - Shows up in grey

### ISSUE THREAD

**Issue by carstenhag** [AppIntro/AppIntro#727]
**AppIntro Version**: 6.0.0-alpha3

**Device/Android Version**: One Plus 5, Android 9

**Issue details / Repro steps / Use case background**: Done button shows up with grey background, not sure how to customize it. Pretty sure I can only change the text color?

`showDoneButton` is deprecated, but the documentes replacement does not exist.

**Your Code**: https://gitlab.com/carstenhag/android-mosbach-map/blob/develop/app/src/main/java/de/chagemann/stadtplanmosbach/IntroActivity.kt

<img width="635" alt="Bildschirmfoto 2020-01-18 um 22 45 42" src="https://user-images.githubusercontent.com/3776997/72670982-46e7b980-3a44-11ea-8173-7cccb64f3bf6.png">

**Comment by cortinico** [comment]
Hi @carstenhag Thanks for reporting.

> showDoneButton is deprecated, but the documentes replacement does not exist.

Thanks for noticing this. Looks like the KDoc was outdated. `showDoneButton` is actually deprecated in favour of `setButtonsEnabled`/`isButtonsEnabled`.

Although your problem is apparently dealing with button background. Currently AppIntro doesn't offer a simple API for customising the button background. 

By default buttons, use the `?attr/selectableItemBackground` theme attribute as background color. 
So you currently have three alternatives:

1. Use a separate theme for your `IntroActivity` and override `?attr/selectableItemBackground` to the color you wish. 

1. Provide your own `AppIntroBase` subclass (as we currently do for `AppIntro` and `AppIntro2`). You can then supply your own `layoutId` that will be used to render the bottom buttons (skip, next, etc. as well as the indicator).

1. Define a style in your theme called `AppIntroButtonStyleCompat`. AppIntro will pick up this style and will use it for the button, overriding the one provided by the library. The one provided by the library is this one:

https://github.com/AppIntro/AppIntro/blob/f71e5153940b795acda39a9609f0c17e8aac062f/appintro/src/main/res/values/styles.xml#L6-L13

I hope I was able to solve your problem.

**Comment by 7200rpm** [comment]
Is there updated guidance for version 6.0.0? I added in the style above it did not work, but gave a background on the next icon, which looks especially ugly. Just want to set the color of the skip button background.

**Comment by 7200rpm** [comment]
> Is there updated guidance for version 6.0.0? I added in the style above it did not work, but gave a background on the next icon, which looks especially ugly. Just want to set the color of the skip button background.

Oh, just kidding, need to use `backgroundTint` like so
```
<item name="android:backgroundTint">@color/colorPrimary</item>
        <item name="android:textColor">@color/white</item>
```
