### ISSUE TITLE
How to go to the latest slide?

### ISSUE THREAD

**Issue by Pirokar** [AppIntro/AppIntro#846]
Didn't find any solution to go to the latest slide when skip is pressed

**Comment by cortinico** [comment]
> Didn't find any solution to go to the latest slide when skip is pressed

This is not allowed as of today. The reason is that you could have `SlidePolicy` or Permissions slides that will be entirely skipped if we allow to arbitrarily jump between slides.

**Comment by Pirokar** [comment]
Hm, why you're just cannot to say:
if(goingToLatrstSlidePressed && someSlideShouldShowBeforeThat) {goToSlideThatShouldShow()} ?
And, interesting, we can skip all intro by open another activity if we can react to skip pressed, but for some not understanding reason we can't to try to show the latest slide.

**Comment by cortinico** [comment]
> if(goingToLatrstSlidePressed 

There is no "goToLastSlidePressed" event. I think you're referring to the _Skip_ button, that is designed with the intention to let the user exit the whole introduction.

> someSlideShouldShowBeforeThat) {goToSlideThatShouldShow()} ?

We don't have this logic at the moment. We would need to go through all the slides, check if they're either a `SlidePolicy` or a Permission slide (with not requested permission). 

> but for some not understanding reason we can't to try to show the latest slide.

What's not clear for you? The reason is: this is currently not supported at the moment.
